<template>
  <q-page class="complaints-page">
    <!-- Full-bleed background image layer -->
    <div class="bg-layer" aria-hidden="true"></div>

    <!-- Content sits on top -->
    <div class="complaints-inner">
      <div class="complaints-header">
        <h1 class="page-title">Complaints</h1>
        <p class="page-subtitle">Dispute heritage information or report monument damage</p>
      </div>

      <div class="complaints-cards">
        <div class="complaint-card" @click="$router.push('/complaints/rectify')">
          <div class="card-icon">
            <q-icon name="edit_note" size="40px" color="primary" />
          </div>
          <h2>Rectify Information</h2>
          <p>If you are a local or historian and wish to dispute or correct information mentioned on the site, submit a formal request here.</p>
          <q-btn flat label="Submit Request" color="primary" class="card-btn" />
        </div>

        <div class="complaint-card" @click="$router.push('/complaints/report')">
          <div class="card-icon">
            <q-icon name="report_problem" size="40px" color="negative" />
          </div>
          <h2>Report Damage</h2>
          <p>If you are visiting a monument and notice damage, upload an image and description so it can be reported to the authorities.</p>
          <q-btn flat label="Report Now" color="negative" class="card-btn" />
        </div>
      </div>
    </div>
  </q-page>
</template>

<script setup>
</script>

<style scoped>
/* Page itself fills the screen — no max-width clipping */
.complaints-page {
  position: relative;
  /*
   * overflow:hidden is required so the absolutely-positioned .bg-layer
   * is clipped to this element's bounds and the global body background-image
   * (explore_bg.png, background-attachment:fixed) cannot bleed through.
   */
  overflow: hidden;
  /* Opaque fallback ensures the body bg is fully occluded even before
     the .bg-layer image finishes loading. */
  background-color: #4a2c1e;
  min-height: 100vh;
  padding: 0;
  margin: 0;
  max-width: 100% !important;
}

/* The actual background image, absolutely positioned behind content */
.bg-layer {
  position: absolute;
  /* We use negative margins/scale to clip out the watermark at the edges */
  inset: -5%;
  background-image: url('@/assets/complaints_bg_new.png');
  background-size: cover;
  background-position: center top;
  background-repeat: no-repeat;
  z-index: 0;
  /* Darken it slightly so the white text/cards pop out better */
  filter: brightness(0.9) contrast(1.1);
  /* Crop out the fake baked-in footer text generated by AI at the bottom */
  clip-path: inset(0 0 10% 0);
}

/* All content floats above bg */
.complaints-inner {
  position: relative;
  z-index: 1;
  max-width: 860px;
  margin: 0 auto;
  /*
   * Bottom padding accounts for the q-footer bottom nav (≈60px) plus
   * iOS safe-area. Using 96px gives comfortable clearance without
   * hard-coding any pixel offset tied to a specific device.
   */
  padding: 56px 24px 96px;
}

.complaints-header {
  text-align: center;
  margin-bottom: 48px;
}

.page-title {
  font-family: 'Cinzel', serif;
  font-size: 2.4rem;
  font-weight: 700;
  color: #2c1800;
  margin: 0 0 10px;
  letter-spacing: 3px;
  text-shadow: 0 1px 8px rgba(255, 240, 200, 0.9);
}

.page-subtitle {
  font-family: 'Cormorant Garamond', serif;
  font-style: italic;
  color: #4a2c0a;
  font-size: 1.15rem;
  letter-spacing: 0.5px;
  margin: 0;
}

.complaints-cards {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 28px;
}

@media (max-width: 600px) {
  .complaints-cards {
    grid-template-columns: 1fr;
  }
  .page-title {
    font-size: 1.8rem;
  }
}

.complaint-card {
  background: rgba(255, 248, 232, 0.90);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
  border-radius: 20px;
  padding: 36px 28px;
  box-shadow: 0 8px 40px rgba(60, 30, 5, 0.2);
  border: 1px solid rgba(212, 160, 23, 0.3);
  cursor: pointer;
  transition: transform 0.25s ease, box-shadow 0.25s ease, border-color 0.25s ease;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.complaint-card:hover {
  transform: translateY(-6px);
  box-shadow: 0 18px 56px rgba(60, 30, 5, 0.28);
  border-color: rgba(212, 160, 23, 0.55);
}

.card-icon {
  line-height: 1;
}

.complaint-card h2 {
  font-family: 'Cinzel', serif;
  font-size: 1.2rem;
  font-weight: 700;
  color: #2c1800;
  margin: 0;
  letter-spacing: 1px;
}

.complaint-card p {
  font-family: 'Cormorant Garamond', serif;
  color: #4a2c0a;
  font-size: 1rem;
  line-height: 1.65;
  margin: 0;
  flex: 1;
}

.card-btn {
  align-self: flex-start;
}
</style>
